### ISSUE TITLE
bootsnapのせいでRailsコマンドが叩けない(仮)

### ISSUE THREAD

**Issue by yuito-syz** [yuito-syz/goodbooking#173]
正確には以下のようなエラーが発生する
```
% rails s 
/Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': dlopen(/Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/sqlite3_native.bundle, 0x0009): Symbol not found: _sqlite3_enable_load_extension (LoadError)
  Referenced from: /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/sqlite3_native.bundle
  Expected in: /usr/lib/libsqlite3.dylib - /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3/sqlite3_native.bundle
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3.rb:6:in `rescue in <main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3.rb:2:in `<main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:55:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:55:in `block in require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:44:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:44:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler.rb:175:in `require'
        from /Users/nemuson/Development/rails/portfolio/config/application.rb:7:in `<main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands/server/server_command.rb:141:in `block in perform'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands/server/server_command.rb:138:in `tap'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands/server/server_command.rb:138:in `perform'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/command/base.rb:69:in `perform'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/command.rb:46:in `invoke'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands.rb:18:in `<main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        from /Users/nemuson/Development/rails/portfolio/bin/rails:9:in `<top (required)>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/nemuson/Development/rails/portfolio/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
/Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require': cannot load such file -- sqlite3/2.6/sqlite3_native (LoadError)
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:40:in `rescue in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:26:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/sqlite3-1.4.1/lib/sqlite3.rb:4:in `<main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:55:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:55:in `block in require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:44:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler/runtime.rb:44:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.32/lib/bundler.rb:175:in `require'
        from /Users/nemuson/Development/rails/portfolio/config/application.rb:7:in `<main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands/server/server_command.rb:141:in `block in perform'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands/server/server_command.rb:138:in `tap'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands/server/server_command.rb:138:in `perform'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/command/base.rb:69:in `perform'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/command.rb:46:in `invoke'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3/lib/rails/commands.rb:18:in `<main>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `block in require'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3/lib/active_support/dependencies.rb:324:in `require'
        from /Users/nemuson/Development/rails/portfolio/bin/rails:9:in `<top (required)>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
        from /Users/nemuson/Development/rails/portfolio/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/nemuson/Development/rails/portfolio/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
bin/rails: Bootsnap::LoadPathCache::FallbackScan
```

**Comment by yuito-syz** [comment]
- [bootsnapのせいでRails5.2とかが動かない人へ](https://qiita.com/cyborg__ninja/items/d15b50500f4ffb069feb)
- [bootsnapについて調べてみた](https://qiita.com/Daniel_Nakano/items/aadeaa7ae4e227b73878)
