### ISSUE TITLE
ゲストログインkinou

### ISSUE THREAD

**Issue by yuito-syz** [yuito-syz/goodbooking#282]

**Comment by yuito-syz** [comment]
- [ ] loggedInPageに遷移しない
- [ ] ActionController::RoutingError (No route matches [POST] "/api/auth/login")

**Comment by yuito-syz** [comment]
- [ ] config/routes.rb
- [ ] app/controllers/users/sessions_controller.rb
- [ ] app/models/user.rb
- [ ] app/controllers/users/registrations_controller.rb
- [ ] app/controllers/users/passwords_controller.rb

**Comment by yuito-syz** [comment]
```sh
Processing by Api::V1::Auth::SessionsController#guest_sign_in as HTML
[Devise] Could not find devise mapping for path "/api/v1/auth/guest_sign_in".
This may happen for two reasons:

1) You forgot to wrap your route inside the scope block. For example:

  devise_scope :user do
    get "/some/route" => "some_devise_controller"
  end

2) You are testing a Devise controller bypassing the router.
   If so, you can explicitly tell Devise which mapping to use:

   @request.env["devise.mapping"] = Devise.mappings[:user]


Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 576)
```

**Comment by yuito-syz** [comment]
`namespace :api do namespace :v1 do end end`に下記を入れた
```ruby
devise_scope :users do
        post "api/v1/auth/guest_sign_in", to: "api/v1/auth/sessions#guest_sign_in"
end
```
すると
```sh
Started POST "/api/v1/auth/guest_sign_in" for ::1 at 2022-03-20 18:34:19 +0900
   (2.0ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
  
ActionController::RoutingError (No route matches [POST] "/api/v1/auth/guest_sign_in"):
  

ArgumentError: wrong number of arguments (given 2, expected 3)
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionview-6.1.4/lib/action_view/base.rb:230:in `initialize'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/web-console-3.7.0/lib/web_console/template.rb:21:in `new'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/web-console-3.7.0/lib/web_console/template.rb:21:in `render'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/web-console-3.7.0/lib/web_console/middleware.rb:37:in `block in call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `catch'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/web-console-3.7.0/lib/web_console/middleware.rb:20:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4/lib/rails/rack/logger.rb:37:in `call_app'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4/lib/rails/rack/logger.rb:26:in `block in call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb:37:in `tagged'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb:99:in `tagged'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4/lib/rails/rack/logger.rb:26:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.4/lib/action_dispatch/middleware/request_id.rb:26:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-6.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.4/lib/action_dispatch/middleware/static.rb:24:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/actionpack-6.1.4/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/webpacker-5.4.3/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rack-proxy-0.7.2/lib/rack/proxy.rb:67:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-6.1.4/lib/rails/engine.rb:539:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/puma-5.6.1/lib/puma/configuration.rb:252:in `call'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/puma-5.6.1/lib/puma/request.rb:77:in `block in handle_request'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/puma-5.6.1/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/puma-5.6.1/lib/puma/request.rb:76:in `handle_request'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/puma-5.6.1/lib/puma/server.rb:441:in `process_client'
	from /Users/nemuson/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/puma-5.6.1/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```
とエラーになった
`users_controller.rb`も
`app/controllers/api/v1/users_controller.rb`から
`app/controllers/api/v1/auth/users_controller.rb`に変更した
